import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const comic = localFont({
  src: "./fonts/RodinHimawariPro-UB.woff2",
  display: "block",
  variable: "--font-comic",
});

export const metadata = {
  title: "Smash Waldo Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${comic.variable} ${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
